# Generated by Django 5.0.1 on 2024-04-08 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price_som',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
    ]
