# Generated by Django 5.0.1 on 2024-04-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_price_som'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_count',
            field=models.PositiveSmallIntegerField(default=1, null=True),
        ),
    ]
