# Generated by Django 5.0.1 on 2024-04-01 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booklike',
            old_name='book_id',
            new_name='book',
        ),
    ]
